# Generated by Django 5.2.3 on 2025-07-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetexpense',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='budget_expense_attachments/'),
        ),
        migrations.AddField(
            model_name='budgetexpense',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budgetexpense',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
