# Generated by Django 5.2.3 on 2025-07-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_budgetexpense_attachment_budgetexpense_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetrevenue',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='budget_revenue_attachments/'),
        ),
        migrations.AddField(
            model_name='budgetrevenue',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budgetrevenue',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
