# Generated by Django 5.2.3 on 2025-07-15 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_budgetrevenue_attachment_budgetrevenue_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=255)),
                ('asset_id', models.CharField(max_length=100, unique=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_from', models.CharField(blank=True, max_length=255)),
                ('manufacturer', models.CharField(blank=True, max_length=255)),
                ('model', models.CharField(blank=True, max_length=255)),
                ('serial_number', models.CharField(blank=True, max_length=255)),
                ('brand', models.CharField(blank=True, max_length=255)),
                ('supplier', models.CharField(blank=True, max_length=255)),
                ('condition', models.CharField(blank=True, max_length=255)),
                ('warranty', models.CharField(blank=True, max_length=100)),
                ('warranty_end', models.DateField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('returned', 'Returned')], default='approved', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('files', models.FileField(blank=True, null=True, upload_to='asset_files/')),
                ('asset_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='core.employee')),
            ],
        ),
    ]
