# Generated by Django 5.2.3 on 2025-07-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_companysettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalizationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_language', models.CharField(choices=[('en', 'English'), ('ur', 'Urdu'), ('ar', 'Arabic')], default='en', max_length=10)),
                ('timezone', models.CharField(choices=[('Asia/Karachi', 'Asia/Karachi'), ('Asia/Dubai', 'Asia/Dubai'), ('UTC', 'UTC')], default='Asia/Karachi', max_length=50)),
                ('date_format', models.CharField(default='%Y-%m-%d', max_length=20)),
                ('time_format', models.CharField(default='%H:%M', max_length=20)),
                ('currency', models.CharField(default='PKR', max_length=10)),
                ('currency_symbol', models.CharField(default='₨', max_length=5)),
                ('thousand_separator', models.CharField(default=',', max_length=2)),
                ('decimal_separator', models.CharField(default='.', max_length=2)),
            ],
        ),
    ]
