# Generated by Django 5.2.3 on 2025-07-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_localizationsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(default='INV-', max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='invoice_logos/')),
            ],
        ),
    ]
