# Generated by Django 5.2.3 on 2025-07-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_invoicesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalarySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('da_enabled', models.BooleanField(default=False)),
                ('da_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('hra_enabled', models.BooleanField(default=False)),
                ('hra_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('pf_enabled', models.BooleanField(default=False)),
                ('pf_employee_share', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('pf_org_share', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('esi_enabled', models.BooleanField(default=False)),
                ('esi_employee_share', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('esi_org_share', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('gratuity_enabled', models.BooleanField(default=False)),
                ('gratuity_employee_share', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('gratuity_org_share', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
    ]
