# Generated by Django 5.2.3 on 2025-07-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_salarysettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(default='SBS HRM', max_length=100)),
                ('logo_light', models.ImageField(blank=True, null=True, upload_to='theme_logos/')),
                ('logo_dark', models.ImageField(blank=True, null=True, upload_to='theme_logos/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='theme_favicons/')),
                ('layout', models.CharField(choices=[('vertical', 'Vertical'), ('horizontal', 'Horizontal')], default='vertical', max_length=20)),
                ('layout_width', models.CharField(choices=[('fluid', 'Fluid'), ('boxed', 'Boxed')], default='fluid', max_length=20)),
                ('color_scheme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('orange', 'Orange'), ('blue', 'Blue'), ('maroon', 'Maroon'), ('purple', 'Purple')], default='light', max_length=20)),
                ('layout_position', models.CharField(choices=[('scrollable', 'Scrollable'), ('fixed', 'Fixed')], default='scrollable', max_length=20)),
                ('topbar_color', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=20)),
                ('sidebar_size', models.CharField(choices=[('default', 'Default'), ('small', 'Small'), ('large', 'Large')], default='default', max_length=20)),
                ('sidebar_view', models.CharField(choices=[('default', 'Default'), ('compact', 'Compact')], default='default', max_length=20)),
                ('sidebar_color', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='dark', max_length=20)),
            ],
        ),
    ]
