# Generated by Django 5.2.4 on 2025-07-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_invoice_invoiceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='can_view_attendance',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='can_view_department',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='can_view_designation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='can_view_holidays',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='can_view_leaves',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='can_view_tasks',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_restricted',
            field=models.BooleanField(default=False),
        ),
    ]
