# Generated by Django 5.2.5 on 2025-08-16 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_attendance_system_updates'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='attendancelog',
            new_name='core_attend_employe_584fa1_idx',
            old_name='core_attendance_employee_123456_idx',
        ),
        migrations.RenameIndex(
            model_name='attendancelog',
            new_name='core_attend_timesta_22ab97_idx',
            old_name='core_attendance_timestamp_123456_idx',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.employee'),
        ),
    ]
