# Generated by Django 5.2.4 on 2025-08-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_core_attendance_employee_123456_idx_core_attend_employe_584fa1_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='last_pay_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='pay_frequency',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('biweekly', 'Bi-weekly'), ('weekly', 'Weekly')], default='monthly', max_length=10),
        ),
        migrations.AddField(
            model_name='payslip',
            name='gross_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payslip',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='payslips/'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payslip',
            name='period_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payslip',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('paid', 'Paid')], default='processed', max_length=10),
        ),
        migrations.AddField(
            model_name='payslip',
            name='total_deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payslip',
            name='total_earnings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
