# Generated by Django 5.2.4 on 2025-08-19 09:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_employee_last_pay_date_employee_pay_frequency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxSlab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default', max_length=100)),
                ('min_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rate_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fixed_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.AddField(
            model_name='payrollitem',
            name='category',
            field=models.CharField(choices=[('base', 'Base Salary'), ('allowance', 'Allowance'), ('bonus', 'Bonus'), ('overtime', 'Overtime'), ('commission', 'Commission'), ('tax', 'Income Tax'), ('pf', 'Provident/Social Security'), ('loan', 'Loan/Advance'), ('custom', 'Custom')], default='custom', max_length=20),
        ),
        migrations.AddField(
            model_name='payrollitem',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollitem',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payrollitem',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monthly_installment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='core.employee')),
            ],
        ),
    ]
