# Generated by Django 5.2.4 on 2025-08-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_taxslab_payrollitem_category_payrollitem_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyPayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(unique=True)),
                ('period_end', models.DateField(unique=True)),
                ('run_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
